opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
grafana:
  enabled: false
prometheus:
  enabled: false
opensearch:
  enabled: false

components:
  flagd:
    resources:
      limits:
        memory: 250Mi    
  accounting:
    enabled: false
  email:
    enabled: false
  load-generator:
    enabled: false
  fraud-detection:
    enabled: false
  shipping:
    enabled: false
  ad:
    podAnnotations:
      ownedBy: josh
      product: otel-demo-app
      costCentre: dynatrace1
      supportInfo: |+
        ## Ad Service Issue Support Information
        The ad service can be debugged within the Live Debugger
        by clicking on this link [Debug Service](${DT_ENDPOINT}/ui/apps/dynatrace.devobs.debugger/redirect/?integration=dashboard&org=${DT_HOST}&labels=[%22k8s.container.name:ad%22])

default:
  env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: "metadata.labels['app.kubernetes.io/component']"
    - name: OTEL_COLLECTOR_NAME
      value: 'dynatrace-collector-opentelemetry-collector'
